name: "submit"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install dependencies
        run: npm install
      - name: Build packages
        run: make packages
      - name: Testing
        run: ls builds/ | grep zip
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v0.0.0
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
